const statusEl = document.getElementById("status");
const gatewayUrlEl = document.getElementById("gatewayUrl");

function render({ decision, settings }) {
  gatewayUrlEl.textContent = settings.gatewayUrl;

  if (!settings.apiToken) {
    statusEl.className = "status unknown";
    statusEl.textContent = "No API token set. Open Settings to paste the token from ~/.sentinel_vision/api_token.txt.";
    return;
  }

  if (!decision) {
    statusEl.className = "status unknown";
    statusEl.textContent = "No decision yet. Make sure the gateway is running (sentinel-wall start or the desktop app).";
    return;
  }

  if (decision.error) {
    statusEl.className = "status unknown";
    statusEl.textContent = `Gateway error: ${decision.error}`;
    return;
  }

  const action = decision.decision;
  const cls = { ALLOW: "allow", PAUSE: "pause", HARD_BLOCK: "block" }[action] || "unknown";
  statusEl.className = `status ${cls}`;
  const riskPct = Math.round((decision.risk_score || 0) * 100);
  statusEl.textContent = `${action} -- ${String(decision.category || "unknown").toUpperCase()} (${riskPct}%)`;
}

chrome.runtime.sendMessage({ type: "GET_LAST_DECISION" }, (resp) => {
  if (resp) render(resp);
});

document.getElementById("openOptions").addEventListener("click", () => {
  chrome.runtime.openOptionsPage();
});

document.getElementById("openDashboard").addEventListener("click", () => {
  // The incident dashboard is a local HTML file generated by the desktop
  // app (~/.sentinel_vision/incidents/security_dashboard.html), not
  // something the gateway serves over HTTP -- an extension has no reliable
  // way to open an arbitrary file:// path on the user's machine without
  // the "file access" permission most users won't have granted. Tell them
  // the command instead of guessing a path.
  statusEl.className = "status unknown";
  statusEl.textContent = "Run 'sentinel-wall dashboard' in a terminal to open the incident dashboard.";
});
